name: trabalho_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  sqflite: ^2.3.3
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  google_sign_in: ^6.2.1
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  google_fonts: ^6.2.1
  http: ^1.2.1
  lottie: ^3.1.0
  audioplayers: ^5.0.0
  image_picker: ^1.1.1
  page_transition: ^2.1.0
  local_auth: ^2.2.0
  image: ^3.0.0
  flutter_local_notifications: ^13.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  # flutter_launcher_icons: "^0.13.1"

# flutter_launcher_icons:
#  android: "launcher_icon"
#  ios: true
#  image_path: "assets/images/icon.png"
#  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/animation/
